name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          check-latest: true
          
      - name: Install dependencies
        run: |
          node -v
          npm -v
          npm ci --legacy-peer-deps
        
      - name: Build application
        run: |
          VITE_BASE_PATH=./ npm run build
          
      - name: Configure Azure Static Web Apps
        run: |
          # Create necessary files in dist directory
          cd dist
          
          # Create a fallback for SPA routing
          cp index.html 404.html
          
          # Copy the staticwebapp.config.json from root to dist
          cp ../staticwebapp.config.json .
          
          # Create a _redirects file for Netlify-style redirects
          echo '/*    /index.html   200' > _redirects
          
          # List files for debugging
          echo "=== Files in dist/ ==="
          ls -la
          
          # Verify staticwebapp.config.json
          echo "\n=== staticwebapp.config.json ==="
          cat staticwebapp.config.json
          
      - name: Create build directory for Azure
        run: |
          # Create build directory structure
          mkdir -p build/assets
          
          # Copy only necessary files from dist
          cp -r dist/index.html build/
          cp dist/404.html build/ 2>/dev/null || true
          cp -r dist/assets/* build/assets/ 2>/dev/null || true
          
          # Copy configuration files
          cp staticwebapp.config.json build/
          
          # Create _redirects file for SPA routing
          echo '/*    /index.html   200' > build/_redirects
          
          # Clean up any unnecessary files
          find build -name '*.map' -delete
          
          # List files for verification
          echo "=== Files in build/ ==="
          find build -type f | sort
          
          echo "\n=== Total file count ==="
          find build -type f | wc -l
          
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 33d6a8db16d582c2e8b324002c8f494c8b8e80929511aaf085bcf4daa51e5b7f06-ac285d03-4a3a-43ec-bed2-2e295ab3752d00f28090e98e210f
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'  # Source directory for the application code
          output_location: 'build'  # Azure expects the built files in a 'build' directory
          skip_app_build: true  # We're handling the build manually
