name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          check-latest: true
          
      - name: Install dependencies
        run: |
          # Print versions for debugging
          node -v
          npm -v
          
          # Install dependencies using npm install instead of ci to update lock file
          npm install --legacy-peer-deps
          
          # Verify lock file is up to date
          git status
          
      - name: Build application
        run: |
          # Build with production settings
          VITE_BASE_PATH=./ npm run build
          
          # Verify build output
          ls -la dist/
          
      - name: Prepare build directory
        run: |
          # Create build directory structure
          mkdir -p build
          
          # Copy only necessary files from dist
          cp -r dist/* build/
          
          # Ensure staticwebapp.config.json exists
          if [ ! -f staticwebapp.config.json ]; then
            echo '{"navigationFallback": {"rewrite": "/index.html","exclude": ["/assets/*","/*.css","/*.js","/*.json"]}}' > staticwebapp.config.json
          fi
          
          # Copy configuration files
          cp staticwebapp.config.json build/
          
          # Create _redirects file for SPA routing
          echo '/*    /index.html   200' > build/_redirects
          
          # Clean up any unnecessary files
          find build -name '*.map' -delete
          
          # List files for verification
          echo "=== Files in build/ ==="
          find build -type f | sort
          
          echo "\n=== Total file count ==="
          find build -type f | wc -l
          
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 33d6a8db16d582c2e8b324002c8f494c8b8e80929511aaf085bcf4daa51e5b7f06-ac285d03-4a3a-43ec-bed2-2e295ab3752d00f28090e98e210f
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'  # Source directory for the application code
          output_location: 'build'  # Azure expects the built files in a 'build' directory
          skip_app_build: true  # We're handling the build manually
