name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          check-latest: true
          
      - name: Install dependencies
        run: |
          # Print versions for debugging
          node -v
          npm -v
          
          # Install dependencies using npm install instead of ci to update lock file
          npm install --legacy-peer-deps
          
          # Verify lock file is up to date
          git status
          
      - name: Build application
        run: |
          # Build with production settings
          VITE_BASE_PATH=./ npm run build
          
          # Verify build output
          ls -la dist/
          
      - name: Prepare build directory
        run: |
          # Create build directory structure
          mkdir -p build
          
          # Copy only essential files from dist
          cp dist/index.html build/
          cp dist/404.html build/ 2>/dev/null || true
          
          # Create assets directory and copy only necessary assets
          mkdir -p build/assets
          
          # Copy only the main CSS and JS files (adjust patterns as needed)
          cp dist/assets/*.css build/assets/ 2>/dev/null || true
          cp dist/assets/*.js build/assets/ 2>/dev/null || true
          
          # Copy other essential assets (images, fonts, etc.)
          mkdir -p build/assets/images
          cp -r dist/assets/images/* build/assets/images/ 2>/dev/null || true
          
          # Create minimal staticwebapp.config.json
          echo '{
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/assets/*", "/*.css", "/*.js", "/*.json"]
            },
            "mimeTypes": {
              ".json": "text/json"
            }
          }' > build/staticwebapp.config.json
          
          # Create _redirects file for SPA routing
          echo '/*    /index.html   200' > build/_redirects
          
          # Verify build directory contents
          echo "=== Build directory structure ==="
          find build -type f | sort
          
          echo "\n=== File count ==="
          find build -type f | wc -l
          
          echo "\n=== Build directory size ==="
          du -sh build/*
          
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: 33d6a8db16d582c2e8b324002c8f494c8b8e80929511aaf085bcf4daa51e5b7f06-ac285d03-4a3a-43ec-bed2-2e295ab3752d00f28090e98e210f
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'  # Source directory for the application code
          output_location: 'build'  # Azure expects the built files in a 'build' directory
          skip_app_build: true  # We're handling the build manually
